### ISSUE TITLE
Clean up deprecations

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/distant.dev#9]
Been awhile since we updated the site. When switching to a static clone of the insiders repo, I noticed a lot of deprecations. Documenting here to fix over time.

### 'materialx.emoji.twemoji' is deprecated.

DeprecationWarning: 'materialx.emoji.twemoji' is deprecated.
Material emoji logic has been officially moved into mkdocs-material
version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
instead of 'materialx.emoji.twemoji' in your 'mkdocs.yml' file.

```
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
```

### 'mkdocs_material_extensions' is deprecated.

'mkdocs_material_extensions' is deprecated and will no longer be
supported moving forward. This is the last release.

*Not sure what this affects and if there is a path forward.*
